apiVersion: v1
kind: Service
metadata:
  name: storage-api-load-balancer
  labels:
        app: storage-api
spec:
  selector:
    app: storage-api
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 14200
    targetPort: http