apiVersion: v1
kind: Service
metadata:
  name: storage-api
  labels:
    app: storage-api
    HealthChecks: "true"
spec:
  selector:
    app: storage-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: http