apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-api
  labels:
    app: storage-api
spec:
  selector:
    matchLabels:
      app: storage-api
  template:
    metadata:
      labels:
        app: storage-api
    spec:
      volumes:
        - name: storage-volume
          persistentVolumeClaim:
            claimName: storage-pvc
      containers:
      - name: storage-api
        image: storage-api
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - name: http
          containerPort: 80
        readinessProbe:
          httpGet:
            path: /hc
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 5
          failureThreshold: 10
          successThreshold: 1
        envFrom:
        - configMapRef:
            name: common-config
        - configMapRef:
            name: storage-api-config
        - secretRef:
            name: storage-api-secret
        volumeMounts:
          - name:  storage-volume
            mountPath:  /VideoSharingPlatform/Storage