apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "../../base"

patches:
  - path: "./patches/deployment.yml"

secretGenerator:
  - name: video-manager-api-secret
    behavior: merge
    envs:
      - "./patches/secret.env"