apiVersion: v1
kind: Service
metadata:
  name: identity-provider
  labels:
    app: identity-provider
    HealthChecks: "true"
spec:
  selector:
    app: identity-provider
  ports:
  - protocol: TCP
    port: 80
    targetPort: http
