image:
  tag: 8.6.2-debian-11-r3
  
global:
  storageClass: persistence-sc
existingConfiguration: logstash-config
resources:
  requests:
    cpu: "100m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"
extraEnvVars:
  - name: ES_JAVA_OPTS
    value: -Xmx512M -Xms512M
  - name: LS_JAVA_OPTS
    value: -Xmx512M -Xms512M