image:
  tag: 3.11.11-debian-11-r0

global:
  storageClass: persistence-sc
auth:
  username: user
  password: password
resources:
  requests:
    cpu: "100m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"
memoryHighWatermark:
  enabled: true
readinessProbe:
  initialDelaySeconds: 30