apiVersion: apps/v1
kind: Deployment
metadata:
  name: community-api
  labels:
    app: community-api
spec:
  selector:
    matchLabels:
      app: community-api
  template:
    metadata:
      labels:
        app: community-api
    spec:
      containers:
      - name: community-api
        image: community-api
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - name: http
          containerPort: 80
        readinessProbe:
          httpGet:
            path: /hc
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 5
          failureThreshold: 10
          successThreshold: 1
        envFrom:
        - configMapRef:
            name: common-config
        - configMapRef:
            name: community-api-config
        - secretRef:
            name: community-api-secret