apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "../../base"

configMapGenerator:
  - name: identity-provider-config
    behavior: merge
    envs:
      - "./patches/config-map.env"

secretGenerator:
  - name: identity-provider-secret
    behavior: merge
    envs:
      - "./patches/secret.env"

images:
  - name: identity-provider
    newName: VAR_CONTAINER_REGISTRY/identity-provider
    newTag: VAR_IMAGE_TAG

patches:
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/imagePullSecrets
        value: [{ name: VAR_IMAGE_PULL_SECRET }]