apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "../../base"

components:
  - "../../components/dev-env"

patches:
  - path: "./patches/storage-classes/persistence.yml"

configMapGenerator:
  - name: common-config
    behavior: merge
    envs:
      - "./patches/config-maps/common.env"