apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - "./resources/logstash/config-map.yml"
  - "./resources/jaeger/service.yml"
  - "./resources/jaeger/stateful-set.yml"

generators:
  - "./generators/rabbitmq.yml"
  - "./generators/mongodb.yml"
  - "./generators/postgres.yml"
  - "./generators/redis.yml"
  - "./generators/elasticsearch.yml"
  - "./generators/logstash.yml"