apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: persistence-sc
provisioner: disk.csi.azure.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer 
allowVolumeExpansion: true  
parameters:
  kind: managed