apiVersion: v1
kind: Service
metadata:
  name: identity-provider-load-balancer
  labels:
        app: identity-provider
spec:
  selector:
    app: identity-provider
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 15100
    targetPort: http