apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "../../base"

configMapGenerator:
  - name: storage-api-config
    behavior: merge
    envs:
      - "./patches/config-map.env"

secretGenerator:
  - name: storage-api-secret
    behavior: merge
    envs:
      - "./patches/secret.env"

images:
  - name: storage-api
    newName: VAR_CONTAINER_REGISTRY/storage-api
    newTag: VAR_IMAGE_TAG

patches:
  - path: "./patches/storage-class.yml"
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/imagePullSecrets
        value: [{ name: VAR_IMAGE_PULL_SECRET }]