apiVersion: v1
kind: Service
metadata:
  name: video-processor-application
  labels:
    app: video-processor-application
    HealthChecks: "true"
spec:
  selector:
    app: video-processor-application
  ports:
  - protocol: TCP
    port: 80
    targetPort: http