apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: video-processor-application-hpa
  labels:
        app: video-processor-application
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: video-processor-application
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Pods
    pods:
      metric:
        name: concurrent_video_processing_tasks_percentage
      target:
        type: AverageValue
        averageValue: "80"
