apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: video-processor-application-service-account-role-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: video-processor-application-service-account
  namespace: default
roleRef:
  kind: Role
  name: pod-updater
  apiGroup: rbac.authorization.k8s.io