apiVersion: v1
kind: LimitRange
metadata:
  name: default-cpu-mem-limit-range
spec:
  limits:
  - type: Container
    default:
      cpu: 500m
      memory: 2Gi
    defaultRequest:
      cpu: 100m
      memory: 256Mi