apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-processor-application
spec:
  template:
    spec:
      containers:
      - name: video-processor-application
        imagePullPolicy: Never