apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "../../base"

secretGenerator:
  - name: users-api-secret
    behavior: merge
    envs:
      - "./patches/secret.env"

images:
  - name: users-api
    newName: VAR_CONTAINER_REGISTRY/users-api
    newTag: VAR_IMAGE_TAG

patches:
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/imagePullSecrets
        value: [{ name: VAR_IMAGE_PULL_SECRET }]