apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "../../base"

images:
  - name: web-status
    newName: VAR_CONTAINER_REGISTRY/web-status
    newTag: VAR_IMAGE_TAG

patches:
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/imagePullSecrets
        value: [{ name: VAR_IMAGE_PULL_SECRET }]