apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jaeger
spec:
  selector:
    matchLabels:
      app: jaeger
  serviceName: jaeger
  replicas: 1
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:1
        ports:
        - protocol: UDP
          containerPort: 6831
        - protocol: UDP
          containerPort: 6832
        - containerPort: 5778
        - containerPort: 16686
        - containerPort: 14268
        - containerPort: 14250
        - containerPort: 9411
        resources:
          requests:
            memory: "512Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "500m"
          